### ISSUE TITLE
Support for SDK technical information events

### ISSUE THREAD

**Issue by olksdr** [getsentry/relay#1853]
Based on the proposal https://github.com/getsentry/sentry-javascript/discussions/7178 we want to introduce an additional capability to `Relay` to be able to accept new type of events, which would cary the SDK's technical information. And more precisely it would be a new envelope item type, see:  https://github.com/getsentry/relay/blob/89c39d37562c1557f3660eb76f235e7d2c0a3c62/relay-server/src/envelope.rs#L76-L116

Initial proposed payload schema could be found in following comment: https://github.com/getsentry/sentry-javascript/discussions/7178#discussioncomment-4971181

#### There are few things to think about:
* storage requirements
  * which parts of the payload should be stored and indexed (store packages information)
  * cardinality of versions
* events deduplication
* naming

#### In the initial implementation we could do just:
* ingest all the tech info events
* minimally deserialize them, so we could deduplicate them and avoid pressure on the processing and storage
* dedicate a Kafka topic to forward the deduplicated events to
* add a minimal index in the analytic db

```[tasklist]
### Tasks
- [ ] Link the final payload schema once it's ready
- [ ] Pull S&S team into the discussion about the storage requirements
- [ ] Add new ItemType and the deduplication for processing
```

**Comment by jan-auer** [comment]
This effort has been discontinued.
