### ISSUE TITLE
Apply default scurbbing to span and breadcrumb data

### ISSUE THREAD

**Issue by cleptric** [getsentry/relay#1855]
We started to ship updates in the PHP SDKs and will ship Python/Ruby soon, where we removed sensitive data from `http.client` span descriptions and moved them into the span data instead. 

This was decided in this [RFC](https://github.com/getsentry/rfcs/blob/main/text/0038-scrubbing-sensitive-data.md).
https://github.com/getsentry/relay/pull/1593 reverted this behavior, as the scrubbing of the span description introduced a regression.

We would now need to scrub the values of `span.data.http.query` and `span.data.http.fragment` as well as `breadcrumb.data.http.query` and `breadcrumb.data.http.fragment` by default in Relay.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/relay/pull/1953
- [ ] https://github.com/getsentry/relay/pull/1955
```

**Comment by cleptric** [comment]
Related to https://github.com/getsentry/team-webplatform-meta/issues/2

**Comment by iker-barriocanal** [comment]
```[tasklist]
# Fields to scrub
- [ ] `span.data.http.query`
- [ ] `span.data.http.fragment`
- [ ] `breadcrumb.data.http.query`
- [ ] `breadcrumb.data.http.fragment`
```
