### ISSUE TITLE
Upgrade sentry-types

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#1875]
A recent upgrade of `sentry-types` had to be reverted in #1872 because it causes panics in request handling.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-rust/pull/554
- [ ] Publish `sentry-types`
- [ ] Upgrade `sentry-types` in Relay
```
