### ISSUE TITLE
Make it impossible to track outcomes for items that remain in the envelope

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#1888]
Before https://github.com/getsentry/relay/pull/1877, we reported rate limiting outcomes for replay items that remained in the envelope. This was possible because `track_outcome` uses the output of `EnvelopeLimiter::enforce`, but that function did not actually remove replays from the envelope:

https://github.com/getsentry/relay/blob/82af3929b38b21fa177a0564dc3e85ee42ed5a01/relay-server/src/utils/rate_limits.rs#L408-L410

Not sure what's the exact solution here, but generally speaking, any function that creates an outcome should _consume_ the item that has been dropped.

```[tasklist]
### Tasks
- [x] Refactor EnvelopeContext: https://github.com/getsentry/relay/pull/1936
- [ ] https://github.com/getsentry/relay/pull/1944
- [x] Wontfix: https://github.com/getsentry/relay/pull/1940
- [x] Make test work without running System
- [x] Wontfix: Make inner envelope private -> Won't work, because we should not update the envelope summary after the event has been extracted.
```

**Comment by jjbayer** [comment]
Outcomes can now be produced right where the envelope items are dropped, but the initial goal of simplifying outcome reporting in rate limits has not been achieved.

Let's take a more top-level look at how to restructure Relay's data flow and the envelope data type (hierarchical containers instead of flat list of items?) instead.
