### ISSUE TITLE
[EPIC] Ensure processed transactions always exist for processed profiles

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#2158]
Because of #2083, it can happen that a processed profile is counted as "accepted" while the corresponding processed transaction is rate limited:

```mermaid
sequenceDiagram
    Ingestion->>+Aggregator: transaction metric
    Ingestion->>+RateLimiter: profile
    RateLimiter->>+Outcomes: profile:accepted
    RateLimiter->>+RateLimiter: update rate limits
    Aggregator->>+RateLimiter: transaction metric
    RateLimiter->>+Outcomes: transaction:rate_limited
```

This violates the requirement that processed profiles are always dropped with their corresponding processed transactions.

A possible solution would be to change the way that we count processed profiles: Instead of counting them in two different places (see [PR description here](https://github.com/getsentry/relay/pull/2054)), add a `has_profile` tag to the transaction counter metric, and define

```
processed_profiles := count(processed_transactions) WHERE has_profile = true
```

We have to make sure that this way of counting does not produce more undesired edge cases though.

```[tasklist]
### Code changes
- [x] relay: Revert PRs around counting profiles. https://github.com/getsentry/relay/pull/2163
- [x] relay: Add `has_profile(s)` tag on `transaction.duration` metric. https://github.com/getsentry/relay/pull/2165
- [x] relay: Update metrics rate limiter to emit `rate_limited` outcome for profiles.
- [x] relay: Make profile category depend on `metrics_extracted` flag (either of the transaction or set it on the profile item itself). https://github.com/getsentry/relay/pull/2166
- [x] sentry: Update metrics billing consumer to emit `accepted` outcome for profiles. https://github.com/getsentry/sentry/pull/50047
```

**Comment by jjbayer** [comment]
- The proposed solution requires that the relationship between transactions and profiles will always be `1 to 0..1`. Unless we encode the number of profiles into the tag value ("1", "2", ...).
- The proposed solution will mean we under-count when transaction metrics are extracted in external relays that do not set the `has_profile` tag yet. We could bump the metrics extraction version, but then we would under-count transactions that get sampled out in external relays (because of https://github.com/getsentry/relay/issues/1631).

**Comment by jjbayer** [comment]
Rollout:

1. Update consumer observing `has_profiles`
2. Update Relays
