### ISSUE TITLE
Expose relay metrics protocol to clients

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/relay#2449]
The StatsD protocol Relay has implemented so far is a DataDog flavor, called the "[DogStatsD protocol](https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics#the-dogstatsd-protocol)". On top of vanilla statsd, this protocol offers these additional options:
1. Tags. This has been implemented from the start
2. Sample rates. Not implemented, TBD.
3. Value packing. Not implemented and should be added.
4. Container IDs. Not implemented, but also not needed.
5. Timestamps. Implemented with a different syntax, can be aligned.

There's no reason that our submission protocol diverges from DogStatsD, so we can implement full compatibility with this protocol. Along with this change, Relay can parse all metric payloads directly into buckets, rather than a separate metric type.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/relay/pull/2460
- [ ] https://github.com/getsentry/relay/pull/2466
- [ ] https://github.com/getsentry/relay/pull/2468
- [ ] https://github.com/getsentry/relay/pull/2470
- [ ] https://github.com/getsentry/relay/pull/2472
- [ ] https://github.com/getsentry/relay/pull/2474
```

**Comment by jan-auer** [comment]
I'll compare with protocols from existing collectors first and then bring forward a proposal for improvements.

**Comment by jan-auer** [comment]
Completed.
