### ISSUE TITLE
[Milestone] Custom Metrics sent to Relay

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/relay#2461]
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/relay/issues/2462
- [ ] https://github.com/getsentry/sentry/issues/55639
- [ ] https://github.com/getsentry/sentry/issues/55644
- [ ] https://github.com/getsentry/sentry/issues/55658
- [ ] https://github.com/getsentry/sentry/issues/55640
```

**Comment by jan-auer** [comment]
Implemented and enabled at 100%.
