### ISSUE TITLE
Update relay to support unsampled metrics in Sentry

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/relay#2463]
It is likely that the volume of unsampled metric datapoints coming from Sentry itself is too high for the existing ingestion relay parser.
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/relay/pull/2483
- [x] Speed up statsd parsing (redundant split/char scans)
- [ ] https://github.com/getsentry/relay/issues/2517
```

**Comment by jan-auer** [comment]
The remaining optimization task is not a critical blocker and has been filed for follow-up.
