### ISSUE TITLE
[EPIC] Move the metrics cardinality limiter to Relay

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#2717]
The performance of metrics queries depends on the number of time series they have to aggregate. To put an upper bound on the number of time series - and thus the number of metric buckets with a unique combination of tag values - the metrics ingestion pipeline has a **cardinality limiter**.

It resides in the metrics indexer consumer, currently causing more than half of its CPU usage and introducing additional latency due to a high number of Redis calls. There are two reasons to move the cardinality limiter out of the indexer consumers: 

1. The limiter currently does not apply to Relay.
2. The indexer consumers are a bottleneck and rely on low-latency high throughput.

# Stage 1

```[tasklist]
### Stage 1 / Re-Implementation
- [ ] https://github.com/getsentry/relay/issues/2719
- [x] Organize a Memstore/Redis Instance (We decided to use the existing Relay Redis for now)
- [x] Pass configuration via global config down from Sentry
- [ ] https://github.com/getsentry/sentry/pull/61028
- [ ] https://github.com/getsentry/sentry/pull/61024
- [ ] https://github.com/getsentry/getsentry/pull/12241
- [ ] https://github.com/getsentry/relay/pull/2745
- [x] ~~`SMISMEMBER` instead of loading the entire set~~ (Needs Redis 6.2)
- [ ] https://github.com/getsentry/relay/pull/2849
- [x] Hookup Cardinality Limiter into existing Processing Pipeline
- [x] Investiage alternative HashSet hasher, e.g. AHash for Redis implementation
- [ ] https://github.com/getsentry/snuba/pull/5349/
- [ ] https://github.com/getsentry/sentry-options-automator/pull/574
- [ ] https://github.com/getsentry/relay/pull/2947
- [ ] https://github.com/getsentry/sentry/pull/63562
- [ ] https://github.com/getsentry/relay/pull/2972
- [ ] https://github.com/getsentry/relay/pull/2990
- [ ] https://github.com/getsentry/relay/pull/2978
- [ ] https://github.com/getsentry/relay/pull/3008
- [ ] https://github.com/getsentry/relay/pull/3020
- [ ] https://github.com/getsentry/relay/pull/3018
- [ ] https://github.com/getsentry/relay/issues/3010
- [ ] https://github.com/getsentry/relay/pull/3029
- [ ] https://github.com/getsentry/relay/pull/3053
- [ ] https://github.com/getsentry/relay/pull/3071
- [ ] https://github.com/getsentry/relay/pull/3076
- [ ] https://github.com/getsentry/ops/pull/9381
- [ ] https://github.com/getsentry/relay/pull/3199
- [ ] https://github.com/getsentry/sentry/pull/66299
- [x] ~~Investigate using the hash as a hashmap hash instead of hashing the hash, e.g. https://crates.io/crates/hash_hasher~~  Performs very badly with certain hashes, minimal gain
```

## Validation

- Metrics
  - Same metrics as in the indexer cardinality limiter
  - Observability if org limits are hit through Sentry Errors and metrics

## Rollout

- New memstore
- Load Test (cardinality), adapt existing indexer load tests
- Rollout in S4S
  - Use a really low sample rate, slowly ramp up the rate
  - Verify indexer limiter is now longer hit
  - Turn off limiter in Indexer
- Rollout in Production
  - Same as above, just more informed decisions

# Stage 2

~~Replace Redis Set with in memory HLL and Bloomfilter, which is repeatedly merged back into Redis to synchronize all nodes.~~

While this is still an option to use either probabilistic data structure in either Redis or Relay, it seems a Bloomfilter can [reduce the amount of bits we store by 50%](https://redis.io/docs/data-types/probabilistic/bloom-filter/#total-size-of-a-bloom-filter) 32 to ~15, while at the same time decreasing lookup and write performance. Our current bottleneck is more likely to be CPU than Storage, so this makes this option less interesting and valuable.

**Comment by jjbayer** [comment]
Ideally we can implement a solution that supports both the existing cardinality limiting and the "product-aware", per-tag limiter for span metrics. A good starting point for a combined solution is trying to come up with a common config format, I had something like this in mind:

For the classic limiter:

```javascript
{
    "scope": {
        "level": "organization",
        "use_case": "transactions"
    },
    "window": 3600,
    "limit": 80000,
    "keep": "first-seen", // keep recording tag combinations until limit is exceeded
    "drop_strategy": "bucket" // drop entire buckets when limit is exceeded
}
```

For a per-tag limiter (most complex version):

```javascript
{
    "scope": {
        "level": "project",
        "use_case": "spans",
        "metric": "d:spans/exclusive_time_light@millisecond",
        // limit specific combination of tags
        "tags": [
            "span.group",
            "transaction"
        ]
    },
    "window": 3600,
    "limit": 1000,
    "keep": {
        "type": "top-k", // maintain list of 1000 slowest spans
        "weight": "span.exclusive_time" // same syntax as sampling rules
    },
    "drop_strategy": {
        // replace tag values for the defined tags with a static value
        "type": "tag",
        "replacement": "<< other >>"
    }
}
```

**Comment by jjbayer** [comment]
For the span group cardinality limiter, we will need to apply the limiting in a different part of the code base, because we want to update the span payload itself if a limit has been reached (e.g. drop a tag). So a common config might not make sense, in fact the only common ground might be the bare-bones cardinality tracker.

We could cleanly separate the cardinality limiting concern from metrics by providing a reusable type like this:

```rust
struct CardinalityLimiter {
    scope: String, // used as prefix for redis entries
    window: u64,   // seconds
    limit: usize,  // maximum number of entries per window
}

impl CardinalityLimiter {
    /// Returns `true` if the entry was successfully inserted.
    ///
    /// Returns `false` if the limit for the current time window has been exceeded.
    pub fn try_insert(&self, entry: impl std::hash::Hash) -> bool;
}
```

**Comment by Dav1dde** [comment]
Enabled in SaaS for some Sentry Orgs now. Seeing some issues with Redis memory consumption. I'll investigate before continuing with the rollout.

**Comment by Dav1dde** [comment]
We have a 50% Rollout rate on SaaS and it looks good. We might want to move the cardinality limits to a separate cluster which has less redundancy to reduce network traffic and increase performance. Otherwise we'll have to slightly increase available memory on the existing cluster before rolling out to 100%.

**Comment by Dav1dde** [comment]
100% Rolled out but not activated due to some product concerns on our side.

**Comment by jernejstrasner** [comment]
@Dav1dde can you elaborate on the product concerns please?

**Comment by Dav1dde** [comment]
We tried rolling it out for our own Sentry org twice now, in both cases this broke something in the performance product. This is not a bug, simply shows that the cardinality limiter is culling excessive cardinality from the metrics, unfortunately this does mean all metrics become unreliable (alerts stop working or fire when they shouldn't).

With the current limits we have configured, this currently does also affect some (10 - 30) customer orgs (although a lot less severe than it does our own org).

Ideally we would work on bringing down the cardinality first, then let the limiter enforce the limits and setup alerts for the product team once the limit is breached again in the future.

@jernejstrasner

**Comment by Dav1dde** [comment]
Implemented passive mode on a per limit basis. We should be able to enable passive mode for a few known orgs and then close our efforts here.

**Comment by Dav1dde** [comment]
Limiter is rolled out for SaaS with the exception of a few known orgs.

**Comment by olksdr** [comment]
The epic is done and we are closing this. 
The cardinality limiter is enabled except few orgs, which will be adjusted later.

Few follow-ups will be created for enabling alerts and monitoring.
