### ISSUE TITLE
Improve rollback and immediate rollout pipelines

### ISSUE THREAD

**Issue by jan-auer** [getsentry/relay#2939]
The Relay deployment pipeline sequentially applies all clusters. For faster changes in one of the clusters or rollbacks, we'll need changes to this pipeline or a new pipeline. 

**Main Goals:**
```[tasklist]
### Tasks
- [x] Add a trigger for fast rollbacks
- [x] Introduce a canary stages for Processing and PoPs
```

**Testing the new pipelines:**
```[tasklist]
### Tasks
- [x] Create the new pipelines
- [x] Test S4S deploys via the new pipelines (redeploying what is currently deployed)
- [x] Test SaaS canary deploys via the new pipelines (redeploying what is currently deployed)
- [x] Test SaaS prod deploys via the new pipelines (redeploying what is currently deployed)
- [x] Test ST deploys via the new pipelines (redeploying what is currently deployed)
- [x] Test rollback pipeline functionality (redeploying what is currently deployed)
- [x] Test rollback pipelines simultaneously?
- [x] Get the pipelines in the hands of the ingest team
```

**Comment by jernejstrasner** [comment]
Hey @IanWoodard, you're on this right? Do you have a rough idea about an ETA? Just approximately.

**Comment by IanWoodard** [comment]
> Hey @IanWoodard, you're on this right? Do you have a rough idea about an ETA? Just approximately.

Yes, I am on it! I am targeting to have the first iteration of the revamped pipelines done by the end of this week. If all goes smoothly, I expect them to be ready for testing by the end of next week. I had a productive meeting with the Ingest team this morning, and we are aligned on the plan. Just moving forward with implementation now.

**Comment by iker-barriocanal** [comment]
I think the following monitors are a good start for the new pipeline

**Processing Relays** 
- https://app.datadoghq.com/monitors/137566884
- https://app.datadoghq.com/monitors/14146876
- https://app.datadoghq.com/monitors/137619914
- https://app.datadoghq.com/monitors/14030245

**PoPs**
- https://app.datadoghq.com/monitors/137575470
- https://app.datadoghq.com/monitors/22592147
- https://app.datadoghq.com/monitors/27804625
- https://app.datadoghq.com/monitors/22634395
- https://app.datadoghq.com/monitors/22635255

**Comment by IanWoodard** [comment]
Quick update @jernejstrasner: The aim is to complete testing and hand over the new pipelines to the ingest team within the next two weeks. The testing phase is taking longer than initially anticipated, primarily due to the time difference which results in delays in getting fixes merged. Once in the hands of the ingest team, I plan to work closely with the team to ensure the updated pipelines meet their needs and make adjustments as needed.

**Comment by IanWoodard** [comment]
Tested the functionality of the new Relay pipelines by re-deploying (to the current version) both Processing and PoPs in all regions. All went smoothly. The next step is to test the rollback pipeline.

**Comment by IanWoodard** [comment]
Successfully tested both rollback pipelines (separately). Next step is to try rolling back both at the same time. @Dav1dde said he would bring this up with the team to make sure it is safe to proceed.

**Comment by Dav1dde** [comment]
@IanWoodard consensus, let's go ahead and do it! At the end we would like a rollback to go out as quickly as possible.
