### ISSUE TITLE
[EPIC] Span ingestion Q1

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#2960]
Groundwork for a span-centered performance product.

```[tasklist]
### Basic ingestion
- [x] Accept standalone and OTel spans
- [x] Emit accepted outcomes for indexed spans. https://github.com/getsentry/relay/issues/2930
- [ ] https://github.com/getsentry/relay/issues/2992
- [ ] https://github.com/getsentry/relay/issues/3079
- [ ] https://github.com/getsentry/relay/issues/3260
- [ ] https://github.com/getsentry/relay/issues/3330
```

## Transition phase

See https://www.notion.so/sentry/A-Span-first-Sentry-4e92d8f998c24d4294abaae13778d903.

```[tasklist]
### Compatibility work
- [ ] https://github.com/getsentry/relay/issues/3278
- [ ] https://github.com/getsentry/relay/issues/3333
- [ ] https://github.com/getsentry/relay/issues/3332
- [x] Allow attachments on spans? (only if transaction-attachments are a thing)
```
