### ISSUE TITLE
[EPIC] Metric Stats

### ISSUE THREAD

**Issue by Dav1dde** [getsentry/relay#3147]
## Description

We need outcomes for DDM / custom metrics.

Outcomes for Metrics are generally a tricky problem for several reasons. Metrics are aggregated in multiple stages, SDKs, customer Relays, pop Relays and processing Relays, which makes giving an accurate number of volume hard. On top of that, volume is just a small scaling factor we have to consider, a much bigger factor is the cardinality of a metric.

Ideally outcomes can capture the volume and the cardinality of a metric.

Outcomes should tell us the volume of a single metric (defined by its MRI) and its cardinality per hour.

Our current outcomes cannot capture this information, we need a new mechanism to collect metric outcomes.

#### Requirements

- Indefinite (?) retention
- Fast enough to query for billing purposes
- Volume and Cardinality needs to be represented
- Sentry UI needs access to show the user
- Billing needs access for billing
-  Bizops needs access to process with their own pipelines (can they query snuba instead of reading the topic?)

#### Why not use Outcomes?

- Outcomes currently don't provide a way to group by metric name (incl. metric type and namespace).
- Cardinality needs to be `max()` aggregated not `sum()`'ed

#### Quantity / Volume

We want to determine the volume of metrics received by the first layer of our infrastructure (PoP-Relays). Client side aggregated metrics are counted with a quantity of `1`.

For example: If Relay receives 500 `statsd` items for a single metric per hour, this metric would be considered to have a volume/quantity of 500 metrics per hour.

#### Cardinality

We are interested in the cardinality of a single metric (MRI) per hour.

Cardinality can be queried from storage or collected through the Relay cardinality limiter.

#### Metric Stats Namespaces

Volume: `c:metric_stats/volume@none`
Tags:
- `mri`: Metric Name/MRI: `<type>:<namespace>/<name>[@<unit>]`
- `mri.type`: Metric Type
- `mri.namespace`: Metric namespace (extracted from the MRI)
- `outcome.id`: Outcome ID, metric outcomes share the same numeric outcome ID with regular outcomes.
- `outcome.reason`: Optional machine readable, free-form reason code.

Cardinality: `g:metric_stats/cardinality@none`
- `mri`: Metric Name/MRI: `<type>:<namespace>/<name>[@<unit>]`
- `mri.type`: Metric Type
- `mri.namespace`: Metric namespace (extracted from the MRI)
- `cardinality.limit`: The cardinality limit id which generated this report.
- `cardinality.window`: Cardinality window size in seconds.
- `cardinality.scope`: Cardinality scope (`name`, `project`, `organization`).

If cardinality is tracked by a `project` or `organization` the `mri*` tags will not be present.

### Examples

Payloads/Metrics emitted from Relay into the generic metrics topic.

##### Volume - Accepted

```json
{
   "org_id":0,
   "project_id":42,
   "name":"c:metric_stats/volume@none",
   "type":"c",
   "value":2.0,
   "timestamp":1712223931,
   "tags":{
        "mri": "d:custom/foo@none",
        "mri.type": "d",
        "mri.namespace": "custom",
        "outcome.id": "0",
   },
   "retention_days":90
}
```

##### Cardinality by Name

```json
{
   "org_id":0,
   "project_id":42,
   "name":"g:metric_stats/cardinality@none",
   "type":"g",
   "value":{
      "last":2.0,
      "min":2.0,
      "max":2.0,
      "sum":2.0,
      "count":1
   },
   "timestamp":1712223931,
   "tags":{
        "mri": "s:custom/bar@none",
        "mri.type": "s",
        "mri.namespace": "custom",
        "cardinality.limit": "custom-limit-with-some-id",
        "cardinality.scope": "name",
        "cardinality.window": "3600",
   },
   "retention_days":90
}
```

##### Cardinality by Type

```json
{
   "org_id":0,
   "project_id":42,
   "name":"g:metric_stats/cardinality@none",
   "type":"g",
   "value":{
      "last":2.0,
      "min":2.0,
      "max":2.0,
      "sum":2.0,
      "count":1
   },
   "timestamp":1712223931,
   "tags":{
        "mri.type": "s",
        "mri.namespace": "custom",
        "cardinality.limit": "custom-limit-with-some-id",
        "cardinality.scope": "type",
        "cardinality.window": "3600",
   },
   "retention_days":90
}
```

## Milestone 1 ✅ - Volume / Happy Path

Implement the happy path ("accepted") for volume metric stats: `c:metric_stats/volume@none`.

```[tasklist]
- [x] Create Kafka Topic -> [OPS-5396](https://github.com/getsentry/ops/pull/9606)
- [ ] https://github.com/getsentry/sentry-kafka-schemas/pull/231
- [ ] https://github.com/getsentry/relay/pull/3254
- [ ] https://github.com/getsentry/relay/pull/3281
- [ ] https://github.com/getsentry/sentry/pull/67221
- [ ] https://github.com/getsentry/sentry-options-automator/pull/929
- [ ] https://github.com/getsentry/ops/pull/9746
- [ ] https://github.com/getsentry/sentry-options-automator/pull/931
- [ ] https://github.com/getsentry/relay/pull/3290
- [ ] https://github.com/getsentry/sentry/pull/67596
```

## Milestone 2 ✅ - Cardinality / Happy Path

Implement the happy path ("accepted") for cardinality metric stats: `g:metric_stats/cardinality@none`.

```[tasklist]
- [ ] https://github.com/getsentry/relay/pull/3313
- [ ] https://github.com/getsentry/relay/pull/3321
- [ ] https://github.com/getsentry/relay/pull/3342
- [ ] https://github.com/getsentry/relay/pull/3360
- [ ] https://github.com/getsentry/sentry/pull/68158
- [ ] https://github.com/getsentry/sentry-options-automator/pull/1033
```

## Milestone 2.5 ✅ - Cardinality by Minute and Project

```[tasklist]
- [ ] https://github.com/getsentry/relay/pull/3438
- [ ] https://github.com/getsentry/sentry/pull/68891
- [ ] https://github.com/getsentry/relay/pull/3437
- [x] Enable per minute cardinality
```

## Milestone 3 ✅ - Negative Outcomes

```[tasklist]
- [ ] https://github.com/getsentry/relay/pull/3452
- [ ] https://github.com/getsentry/relay/pull/3389
- [ ] https://github.com/getsentry/sentry/pull/68422
- [ ] https://github.com/getsentry/relay/issues/3433
- [ ] https://github.com/getsentry/relay/issues/3434
- [ ] https://github.com/getsentry/relay/issues/3435
- [ ] https://github.com/getsentry/relay/issues/3482
- [ ] https://github.com/getsentry/relay/pull/3436
```

## Milestone 4 - Finishing Touches

```[tasklist]
- [ ] https://github.com/getsentry/relay/pull/3565
- [ ] https://github.com/getsentry/relay/pull/3569
- [ ] https://github.com/getsentry/ops/pull/10501
- [ ] https://github.com/getsentry/ops/pull/10345
- [ ] https://github.com/getsentry/relay/pull/3626
- [ ] https://github.com/getsentry/relay/pull/3629
- [x] ~~Configurable/Longer Retention~~
- [ ] Check for missing integration tests (prime candidate: rate limits -> negative outcomes)
- [x] Come up with a better way to reject metrics than our current util function
- [x] Figure out `BucketViews` and volume
- [ ] `check_buckets` drops buckets without `reject_metrics`
- [ ] Cardinality Limits are overlapping, if a limit rejects a metric, all other limits are still increased
- [ ] https://github.com/getsentry/relay/pull/3609
- [ ] https://github.com/getsentry/relay/pull/3612
- [ ] https://github.com/getsentry/relay/pull/3582
```

[OPS-5396]: https://getsentry.atlassian.net/browse/OPS-5396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mcannizz** [comment]
@Dav1dde I am wondering if this work is still in flight, and whether we consider that work to be P0. It seems like the remaining tasks are lower priority. If you agree, could you please move the remaining stuff to a lower priority epic and close this one?

**Comment by Dav1dde** [comment]
I would like to keep the Epic open, we are at a stage where we provide all the data which is needed now but we're not at a stage that this data will stay correct with upcoming features. 
E.g. currently metric_stats does not interact well with user defined cardinality limits which the product is already planning. 

Basically at this point we implemented the minimum set everyone else needs but the remaining legwork in Relay is as important just not visible to anyone outside of ingest.

That being said, if moving the remaining tasks to a new Epic makes stuff easier for you I am not opposed to it.

**Comment by mcannizz** [comment]
@Dav1dde makes sense, thanks. I'm going to leave this epic as is but reduce it's priority since it sounds like we've completed the P0 work. Feel free to adjust as you see fit.

**Comment by Dav1dde** [comment]
Closing this, we got all the important bits in place and with the current restructure of the metrics product the remaining pieces are not as important anymore.
