### ISSUE TITLE
Apply inbound filters to spans (using abstraction layer)

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#3317]
```[tasklist]
### Tasks
- [ ] Implement trait introduced in https://github.com/getsentry/relay/pull/3397 for type `Span`.
- [ ] https://github.com/getsentry/relay/issues/3550
- [ ] https://github.com/getsentry/relay/issues/3551
```

**Comment by jjbayer** [comment]
Set Apr 9 as due date, because Replays depend on the abstraction layer as well.

**Comment by jjbayer** [comment]
New due date is Apr 30, because Replays are already unbocked by https://github.com/getsentry/relay/pull/3397.
