### ISSUE TITLE
[EPIC] Extrapolation for extracted metrics

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#3724]
Sentry SDKs use client-side sampling to lower the amount of spans and traces they collect and send to Sentry. Through sampling, clients achieve lower overheads inside the instrumented application, reduce duplicated information sent to Sentry, and also control the ingestion volume which the organization is charged by.

In the past, client-side sampling was not incorporated into the numbers shown in Sentry’s UI; only data that made it to Sentry counts. This is subject to change. Sentry’s product will aim to accurately reflect real performance data, even when only a subset of spans are sampled and analyzed.

This can be achieved by extrapolating from the sampled data. Initially, we deliver extrapolation for metrics extracted from tracing data — transaction, span, and custom metrics — and later be expanded to individual event data.

## Details

We will apply weights directly within Relay during the metrics extraction process, before inserting the values into the metrics aggregator. 

- **Counters**: Multiply with `1/sample_rate`.
Since counters accumulate values, we need to scale up the counted values based on the sample rate to estimate the total count accurately. For example, if the sample rate is 0.1 (10%), each count will be multiplied by 10 (i.e., `1/0.1`) to reflect the estimated total count.
- **Set**: Do nothing.
Sets are used to track unique values, and the cardinality of unique values cannot be extrapolated with any statistical significance.. Hence, no adjustment is needed for sets.
- **Gauges**: Multiply `.sum` and `.count` with `1/sample_rate`.
Gauges act like simplified distributions. Since we cannot assume anything about the distribution-type fields like min or max, those remain unchanged. The sum and count field resemble a counter and thus get extrapolated in the same strategy as a counter.
- **Distributions**: Insert duplicates with `round(1/sample_rate)`
For distribution metrics, we need to account for changing sample rates over time. By expanding (i.e. duplicating) values based on the rounded inverse of the sample rate, we can emulate weights with reasonable accuracy. For example, if the sample rate is 0.2 (20%), each value in the distribution is inserted `round(1/0.2)` = 5 times.

The wire format for metric payloads remains unchanged. To protect against unbounded expansion, there will be a configurable upper bound to the duplication factor that applies exclusively to distributions. The option for this is part of the metric extraction configuration.

## Resources

- [**Project Doc**](https://www.notion.so/sentry/Metrics-Extrapolation-a5e2fd4ed854400d81792e85ae6e0732)
- [**Tech Spec**](https://www.notion.so/sentry/Metrics-Extrapolation-520ab136cb7d48ebb77be9a538bdef91)
- [**Discarded Alternatives**](https://www.notion.so/sentry/Tech-Spec-Metrics-Extrapolation-520ab136cb7d48ebb77be9a538bdef91?pvs=4#7c3e28bd03694ece93b0570aa5448d62)

```[tasklist]
### Preparation
- [ ] https://github.com/getsentry/relay/issues/3738
```

```[tasklist]
### Custom Span Attributes
- [ ] https://github.com/getsentry/relay/pull/3753
- [ ] https://github.com/getsentry/sentry/pull/73289
- [ ] https://github.com/getsentry/sentry/issues/73185
- [ ] https://github.com/getsentry/sentry/issues/73623
- [ ] https://github.com/getsentry/team-ingest/issues/366
```

```[tasklist]
### Internal Test: Spans and Transactions
- [x] Add a temporary setting for transaction / spans metrics
- [ ] https://github.com/getsentry/team-ingest/issues/365
- [ ] https://github.com/getsentry/team-ingest/issues/372
- [ ] https://github.com/getsentry/sentry/issues/74340
- [x] https://github.com/getsentry/sentry-options-automator/pull/2015
- [ ] https://github.com/getsentry/sentry-options-automator/pull/2027
- [x] Enable for Sentry
```

```[tasklist]
### Public: Spans and Transactions
- [ ] https://github.com/getsentry/team-ingest/issues/369
- [ ] https://github.com/getsentry/sentry/issues/73186
- [ ] https://github.com/getsentry/sentry/issues/76657
- [ ] https://github.com/getsentry/sentry/issues/76654
- [ ] https://github.com/getsentry/sentry/issues/76655
- [ ] https://github.com/getsentry/sentry/issues/76656
- [ ] https://github.com/getsentry/sentry/issues/76653
```

```[tasklist]
### Query-Time Extrapolation
- [ ] https://github.com/getsentry/team-ingest/issues/374
- [ ] https://github.com/getsentry/sentry-kafka-schemas/pull/324
- [ ] https://github.com/getsentry/sentry/pull/75425
- [ ] https://github.com/getsentry/relay/pull/3884
```

**Comment by iambriccardo** [comment]
I am not an expert but given two buckets `b1` and `b2` with weights `w1` and `w2`, if you sum `w1 + w2` during merge you will not get the equivalent extrapolation as if you were to compute it correctly as as `1.0 / ((b1 * w1) + (b2 * w2) / (b1 + b2))`.

I may be missing something though.

**Comment by jan-auer** [comment]
Extrapolation will be added to the Trace Explorer on the Event Analytics Platform, instead.
