### ISSUE TITLE
Add ability to rate limit the number of attachments

### ISSUE THREAD

**Issue by jjbayer** [getsentry/relay#4175]
Attachment quotas and rate limits are currently defined in bytes, so we have no way to prevent an abusively high number of very small attachments.

https://www.notion.so/sentry/Data-category-for-attachment-items-1518b10e4b5d80c8aec7fecaa0e53af6

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/relay/pull/4374
- [x] Bump relay version in sentry and snuba
- [x] Enforce rate limits and report outcomes in relay
- [x] Define a project abuse limit (sentry side)
```

ref: [INC-928](https://getsentry.atlassian.net/browse/INC-928) > [IA-61](https://getsentry.atlassian.net/browse/IA-61)

[INC-928]: https://getsentry.atlassian.net/browse/INC-928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IA-61]: https://getsentry.atlassian.net/browse/IA-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jjbayer** [comment]
Bumping to P1 because it blocks resolution of INC-928.

**Comment by jjbayer** [comment]
We will add a new data category, but in relay internally experiment with the concept of a "unit".

https://www.notion.so/sentry/Data-category-for-attachment-items-1518b10e4b5d80c8aec7fecaa0e53af6
